### ISSUE TITLE
how to use elevation in config file ? i have this error

### ISSUE THREAD

**Issue by axizof** [Wardenfar/Osm2Map#1]
Hello, how to use elevation in the configuration file when I try to set the elevation to true I get this error I don't know if it's an error or I'm doing wrong,
log--
```
[21:19:41] [Server thread/INFO]: Starting minecraft server version 1.12.2
[21:19:41] [Server thread/INFO]: Loading properties
[21:19:41] [Server thread/INFO]: Default game type: SURVIVAL
[21:19:41] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[21:19:42] [Server thread/INFO]: Debug logging is disabled
[21:19:42] [Server thread/INFO]: Server Ping Player Sample Count: 12
[21:19:42] [Server thread/INFO]: Using 4 threads for Netty based IO
[21:19:42] [Server thread/INFO]: Generating keypair
[21:19:43] [Server thread/INFO]: Starting Minecraft server on *:25565
[21:19:43] [Server thread/INFO]: Using default channel type
[21:19:44] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[21:19:45] [Server thread/INFO]: [FastAsyncWorldEdit] Loading FastAsyncWorldEdit v21.03.26-b67f782-1287-22.3.10
[21:19:45] [Server thread/INFO]: [osm2map] Loading osm2map v3.2
[21:19:45] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v6.1.7;dd00bb1
[21:19:45] [Server thread/INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v21.03.26-b67f782-1287-22.3.10
[21:19:46] [Server thread/INFO]: [0;35;1mVault is used for persistent `/wea` toggles.[m
[21:19:46] [Server thread/INFO]: ====== USE PAPER ======[m
[21:19:46] [Server thread/INFO]: DOWNLOAD: https://ci.destroystokyo.com/job/PaperSpigot/[m
[21:19:46] [Server thread/INFO]: GUIDE: https://www.spigotmc.org/threads/21726/[m
[21:19:46] [Server thread/INFO]:  - This is only a recommendation[m
[21:19:46] [Server thread/INFO]: ==============================[m
[21:19:46] [Server thread/INFO]: [osm2map] Enabling osm2map v3.2
[21:19:47] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[21:19:47] [Server thread/INFO]: Preparing level "world"
[21:19:47] [Server thread/INFO]: -------- World Settings For [world] --------
[21:19:47] [Server thread/INFO]: Item Merge Radius: 2.5
[21:19:47] [Server thread/INFO]: Item Despawn Rate: 6000
[21:19:47] [Server thread/INFO]: Arrow Despawn Rate: 1200
[21:19:47] [Server thread/INFO]: View Distance: 10
[21:19:47] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[21:19:47] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[21:19:47] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[21:19:47] [Server thread/INFO]: Random Lighting Updates: false
[21:19:47] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[21:19:47] [Server thread/INFO]: Cactus Growth Modifier: 100%
[21:19:47] [Server thread/INFO]: Cane Growth Modifier: 100%
[21:19:47] [Server thread/INFO]: Melon Growth Modifier: 100%
[21:19:47] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[21:19:47] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[21:19:47] [Server thread/INFO]: Sapling Growth Modifier: 100%
[21:19:47] [Server thread/INFO]: Wheat Growth Modifier: 100%
[21:19:47] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[21:19:47] [Server thread/INFO]: Vine Growth Modifier: 100%
[21:19:47] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[21:19:47] [Server thread/INFO]: Mob Spawn Range: 4
[21:19:47] [Server thread/INFO]: Structure Info Saving: true
[21:19:47] [Server thread/INFO]: Max TNT Explosions: 100
[21:19:47] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[21:19:47] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[21:19:47] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[21:19:47] [Server thread/INFO]: Experience Merge Radius: 3.0
[21:19:47] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[21:19:47] [Server thread/INFO]: [osm2map] Create DB ...plugins\osm2map\paris-o2m.db
[21:19:48] [Server thread/INFO]: Create Schema ...
[21:19:50] [Server thread/INFO]: Ways : 0/455
[21:19:51] [Server thread/INFO]: [osm2map] Load ElevationData ...
[21:19:51] [Server thread/WARN]: java.lang.NullPointerException
[21:19:51] [Server thread/WARN]: 	at com.wardenfar.osm2map.Osm2map.initWorld(Osm2map.java:365)
[21:19:51] [Server thread/WARN]: 	at com.wardenfar.osm2map.Osm2map.onWorldInitEvent(Osm2map.java:218)
[21:19:51] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:19:51] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:19:51] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:19:51] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:19:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[21:19:51] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[21:19:51] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[21:19:51] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[21:19:51] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:325)
[21:19:51] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[21:19:51] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[21:19:51] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[21:19:51] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[21:19:51] [Server thread/INFO]: Item Merge Radius: 2.5
[21:19:51] [Server thread/INFO]: Item Despawn Rate: 6000
[21:19:51] [Server thread/INFO]: Arrow Despawn Rate: 1200
[21:19:51] [Server thread/INFO]: View Distance: 10
[21:19:51] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[21:19:51] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[21:19:51] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[21:19:51] [Server thread/INFO]: Random Lighting Updates: false
[21:19:51] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[21:19:51] [Server thread/INFO]: Cactus Growth Modifier: 100%
[21:19:51] [Server thread/INFO]: Cane Growth Modifier: 100%
[21:19:51] [Server thread/INFO]: Melon Growth Modifier: 100%
[21:19:51] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[21:19:51] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[21:19:51] [Server thread/INFO]: Sapling Growth Modifier: 100%
[21:19:51] [Server thread/INFO]: Wheat Growth Modifier: 100%
[21:19:51] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[21:19:51] [Server thread/INFO]: Vine Growth Modifier: 100%
[21:19:51] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[21:19:51] [Server thread/INFO]: Mob Spawn Range: 4
[21:19:51] [Server thread/INFO]: Structure Info Saving: true
[21:19:51] [Server thread/INFO]: Max TNT Explosions: 100
[21:19:51] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[21:19:51] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[21:19:51] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[21:19:51] [Server thread/INFO]: Experience Merge Radius: 3.0
[21:19:51] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[21:19:51] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[21:19:51] [Server thread/INFO]: Item Merge Radius: 2.5
[21:19:51] [Server thread/INFO]: Item Despawn Rate: 6000
[21:19:51] [Server thread/INFO]: Arrow Despawn Rate: 1200
[21:19:51] [Server thread/INFO]: View Distance: 10
[21:19:51] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[21:19:51] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[21:19:51] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[21:19:51] [Server thread/INFO]: Random Lighting Updates: false
[21:19:51] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[21:19:51] [Server thread/INFO]: Cactus Growth Modifier: 100%
[21:19:51] [Server thread/INFO]: Cane Growth Modifier: 100%
[21:19:51] [Server thread/INFO]: Melon Growth Modifier: 100%
[21:19:51] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[21:19:51] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[21:19:51] [Server thread/INFO]: Sapling Growth Modifier: 100%
[21:19:51] [Server thread/INFO]: Wheat Growth Modifier: 100%
[21:19:51] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[21:19:51] [Server thread/INFO]: Vine Growth Modifier: 100%
[21:19:51] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[21:19:51] [Server thread/INFO]: Mob Spawn Range: 4
[21:19:51] [Server thread/INFO]: Structure Info Saving: true
[21:19:51] [Server thread/INFO]: Max TNT Explosions: 100
[21:19:51] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[21:19:51] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[21:19:51] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[21:19:51] [Server thread/INFO]: Experience Merge Radius: 3.0
[21:19:51] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[21:19:52] [Server thread/INFO]: Preparing start region for level 0 (Seed: 6046290189244492220)
[21:19:53] [Server thread/INFO]: Preparing spawn area: 0%
[21:19:53] [Server thread/INFO]: [osm2map] Create DB ...plugins\osm2map\paris-o2m.db
[21:19:53] [Server thread/INFO]: Create Schema ...
[21:19:54] [Server thread/INFO]: Ways : 0/455
[21:19:55] [Server thread/INFO]: [osm2map] Load ElevationData ...
[21:19:55] [Server thread/WARN]: java.lang.NullPointerException
[21:19:55] [Server thread/WARN]: 	at com.wardenfar.osm2map.Osm2map.initWorld(Osm2map.java:365)
[21:19:55] [Server thread/WARN]: 	at com.wardenfar.osm2map.terrainGeneration.OsmElevGenerator.init(OsmElevGenerator.java:46)
[21:19:55] [Server thread/WARN]: 	at com.wardenfar.osm2map.terrainGeneration.OsmElevGenerator.generateChunkData(OsmElevGenerator.java:71)
[21:19:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.generator.CustomChunkGenerator.getOrCreateChunk(CustomChunkGenerator.java:52)
[21:19:55] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:160)
[21:19:55] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:140)
[21:19:55] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120)
[21:19:55] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116)
[21:19:55] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:374)
[21:19:55] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[21:19:55] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[21:19:55] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[21:19:55] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[21:19:55] [Server thread/INFO]: [osm2map] Create DB ...plugins\osm2map\paris-o2m.db
[21:19:55] [Server thread/INFO]: Create Schema ...
[21:19:55] [Server thread/INFO]: Ways : 0/455
[21:19:56] [Server thread/INFO]: [osm2map] Load ElevationData ...
[21:19:56] [Server thread/WARN]: java.lang.NullPointerException
[21:19:56] [Server thread/WARN]: 	at com.wardenfar.osm2map.Osm2map.initWorld(Osm2map.java:365)
[21:19:56] [Server thread/WARN]: 	at com.wardenfar.osm2map.terrainGeneration.OsmElevGenerator.init(OsmElevGenerator.java:46)
[21:19:56] [Server thread/WARN]: 	at com.wardenfar.osm2map.terrainGeneration.OsmElevGenerator.populate(OsmElevGenerator.java:96)
[21:19:56] [Server thread/WARN]: 	at com.wardenfar.osm2map.terrainGeneration.OsmElevGenerator.generateChunkData(OsmElevGenerator.java:82)
[21:19:56] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.generator.CustomChunkGenerator.getOrCreateChunk(CustomChunkGenerator.java:52)
[21:19:56] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:160)
[21:19:56] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:140)
[21:19:56] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120)
[21:19:56] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116)
[21:19:56] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:374)
[21:19:56] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[21:19:56] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[21:19:56] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[21:19:56] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[21:19:56] [Server thread/INFO]: Preparing spawn area: 1%
[21:19:56] [Server thread/INFO]: [osm2map] Create DB ...plugins\osm2map\paris-o2m.db
[21:19:56] [Server thread/INFO]: Create Schema ...
[21:19:57] [Server thread/INFO]: Ways : 0/455
[21:19:57] [Server thread/INFO]: [osm2map] Load ElevationData ...
[21:19:57] [Server thread/WARN]: java.lang.NullPointerException
[21:19:57] [Server thread/WARN]: 	at com.wardenfar.osm2map.Osm2map.initWorld(Osm2map.java:365)
[21:19:57] [Server thread/WARN]: 	at com.wardenfar.osm2map.terrainGeneration.OsmElevGenerator.init(OsmElevGenerator.java:46)
[21:19:57] [Server thread/WARN]: 	at com.wardenfar.osm2map.terrainGeneration.OsmElevGenerator.generateChunkData(OsmElevGenerator.java:71)
[21:19:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.generator.CustomChunkGenerator.getOrCreateChunk(CustomChunkGenerator.java:52)
[21:19:57] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:160)
[21:19:57] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:140)
[21:19:57] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120)
[21:19:57] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116)
[21:19:57] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:374)
[21:19:57] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[21:19:57] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[21:19:57] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[21:19:57] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[21:19:57] [Server thread/INFO]: [osm2map] Create DB ...plugins\osm2map\paris-o2m.db
[21:19:57] [Server thread/INFO]: Create Schema ...
[21:19:58] [Server thread/INFO]: Ways : 0/455
[21:19:58] [Server thread/INFO]: [osm2map] Load ElevationData ...
[21:19:58] [Server thread/WARN]: java.lang.NullPointerException
[21:19:58] [Server thread/WARN]: 	at com.wardenfar.osm2map.Osm2map.initWorld(Osm2map.java:365)
[21:19:58] [Server thread/WARN]: 	at com.wardenfar.osm2map.terrainGeneration.OsmElevGenerator.init(OsmElevGenerator.java:46)
[21:19:58] [Server thread/WARN]: 	at com.wardenfar.osm2map.terrainGeneration.OsmElevGenerator.populate(OsmElevGenerator.java:96)
[21:19:58] [Server thread/WARN]: 	at com.wardenfar.osm2map.terrainGeneration.OsmElevGenerator.generateChunkData(OsmElevGenerator.java:82)
[21:19:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.generator.CustomChunkGenerator.getOrCreateChunk(CustomChunkGenerator.java:52)
[21:19:58] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:160)
[21:19:58] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:140)
[21:19:58] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120)
[21:19:58] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116)
[21:19:58] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:374)
[21:19:58] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[21:19:58] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[21:19:58] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[21:19:58] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[21:19:58] [Server thread/INFO]: ElevFile not found x=1936,z=32
[21:19:58] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_12_R1.ReportedException: Exception generating new chunk
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:168) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:140) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:374) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NullPointerException
	at com.wardenfar.osm2map.Osm2map.getSatelliteBlock(Osm2map.java:594) ~[?:?]
	at com.wardenfar.osm2map.terrainGeneration.OsmElevGenerator.populate(OsmElevGenerator.java:165) ~[?:?]
	at com.wardenfar.osm2map.terrainGeneration.OsmElevGenerator.generateChunkData(OsmElevGenerator.java:82) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.generator.CustomChunkGenerator.getOrCreateChunk(CustomChunkGenerator.java:52) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:160) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	... 8 more
[21:19:58] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.NullPointerException: null
	at com.wardenfar.osm2map.Osm2map.getSatelliteBlock(Osm2map.java:594) ~[?:?]
	at com.wardenfar.osm2map.terrainGeneration.OsmElevGenerator.populate(OsmElevGenerator.java:165) ~[?:?]
	at com.wardenfar.osm2map.terrainGeneration.OsmElevGenerator.generateChunkData(OsmElevGenerator.java:82) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.generator.CustomChunkGenerator.getOrCreateChunk(CustomChunkGenerator.java:52) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:160) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:140) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:374) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[21:19:58] [Server thread/INFO]: Stopping server
[21:19:58] [Server thread/INFO]: [osm2map] Disabling osm2map v3.2
[21:19:58] [Server thread/INFO]: [osm2map] Close Database
[21:19:58] [Server thread/INFO]: [FastAsyncWorldEdit] Disabling FastAsyncWorldEdit v21.03.26-b67f782-1287-22.3.10
[21:19:58] [Server thread/INFO]: Saving players
[21:19:59] [Server thread/INFO]: Saving worlds
[21:19:59] [Server thread/INFO]: Saving chunks for level 'world'/overworld
[21:19:59] [Server thread/INFO]: Saving chunks for level 'world_nether'/the_nether
[21:19:59] [Server thread/INFO]: Saving chunks for level 'world_the_end'/the_end
```

ps:very good plugins easy to use in anyway congratulations.

**Comment by Wardenfar** [comment]
Hello,
The elevation won't work without some data files.
Currently its a custom format and I don't have posted the code. The problem is that I don't have found a site on which you can download the world data.
Thanks
