### ISSUE TITLE
Missing methods

### ISSUE THREAD

**Issue by Slord6** [Wardenfar/Osm2Map#2]
Hi, I'm having trouble running the plugin with [Spigot 1.12.2](https://getbukkit.org/get/Fpt2yFn7HRTrot5uE1b8NFWtpQlYITgK) which complains of missing methods.

```
Time: 25/10/21 13:03
Description: Exception generating new chunk

java.lang.UnsupportedOperationException: Custom generator is missing required methods: generate(), generateBlockSections() and generateExtBlockSections()
	at org.bukkit.generator.ChunkGenerator.generate(ChunkGenerator.java:78)
	at org.bukkit.craftbukkit.v1_12_R1.generator.CustomChunkGenerator.getOrCreateChunk(CustomChunkGenerator.java:128)
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:160)
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:140)
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120)
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116)
	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.loadChunk(CraftWorld.java:271)
	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.loadChunk(CraftWorld.java:162)
	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getHighestBlockYAt(CraftWorld.java:104)
	at org.bukkit.generator.ChunkGenerator.canSpawn(ChunkGenerator.java:270)
	at net.minecraft.server.v1_12_R1.WorldServer.canSpawn(WorldServer.java:261)
	at net.minecraft.server.v1_12_R1.WorldServer.b(WorldServer.java:1003)
	at net.minecraft.server.v1_12_R1.WorldServer.a(WorldServer.java:925)
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:277)
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Wardenfar** [comment]
Hello
Have you the very last version of spigot 1.12.2 ?  This seems that the problem is an imcompatibility of version between the server and the plugin.

**Comment by Slord6** [comment]
I thought that might be the case. I'm pretty sure I'm running the latest version, it's the one listed on [getbukkit.org/download/spigot](https://getbukkit.org/download/spigot):

```
Loading libraries, please wait...
[14:08:48 INFO]: Starting minecraft server version 1.12.2
[14:08:48 INFO]: Loading properties
[14:08:48 INFO]: Default game type: SURVIVAL
[14:08:49 INFO]: This server is running CraftBukkit version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
```
