### ISSUE TITLE
Could not pass event: WorldInitEvent and WorldLoadEvent

### ISSUE THREAD

**Issue by Spantey23** [Wardenfar/Osm2Map#3]
After starting the server and making the necessary pre-settings, the plugin started to create the schema but then aborted with the error: Could not pass event WorldInitEvent
and thus has the further error: Could not pass event WorldLoadEvent thrown.

`Could not pass event WorldInitEvent to osm2map v3.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [craftbukkit.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [craftbukkit.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:325) [craftbukkit.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [craftbukkit.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [craftbukkit.jar:git-Spigot-79a30d7-f4830a1]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_311]
Caused by: java.lang.OutOfMemoryError: Java heap space
        at com.slimjars.dist.gnu.trove.map.hash.TLongObjectHashMap.rehash(TLongObjectHashMap.java:157) ~[?:?]
        at com.slimjars.dist.gnu.trove.impl.hash.THash.postInsertHook(THash.java:418) ~[?:?]
        at com.slimjars.dist.gnu.trove.map.hash.TLongObjectHashMap.doPut(TLongObjectHashMap.java:247) ~[?:?]
        at com.slimjars.dist.gnu.trove.map.hash.TLongObjectHashMap.put(TLongObjectHashMap.java:221) ~[?:?]
        at com.wardenfar.shade.de.topobyte.osm4j.core.dataset.MapDataSetLoader.read(MapDataSetLoader.java:91) ~[?:?]
        at com.wardenfar.osm2map.map.DBMapData.readFromOsmXML(DBMapData.java:105) ~[?:?]
        at com.wardenfar.osm2map.Osm2map.initWorld(Osm2map.java:355) ~[?:?]
        at com.wardenfar.osm2map.Osm2map.onWorldInitEvent(Osm2map.java:218) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit.jar:git-Spigot-79a30d7-f4830a1]
        ... 7 more`

`Could not pass event WorldLoadEvent to osm2map v3.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [craftbukkit.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [craftbukkit.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:380) [craftbukkit.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [craftbukkit.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [craftbukkit.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [craftbukkit.jar:git-Spigot-79a30d7-f4830a1]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_311]
Caused by: java.lang.NullPointerException
        at com.wardenfar.osm2map.Osm2map.onWorldLoadEvent(Osm2map.java:229) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit.jar:git-Spigot-79a30d7-f4830a1]
        ... 8 more`

**Comment by Wardenfar** [comment]
> java.lang.OutOfMemoryError: Java heap space at

Your map is probably too large, try a smaller map like 5km x 5km.
If you just want a map but not the all plugin (permissions, ...) : i have made another project that output a map similar. (1000x faster) with few limitations like teleportation, commands, ...
https://github.com/Wardenfar/mc-osm-world-gen
